Remove a simple warning about missing template keyword
Fixes GCC 12 warning:

openvdb/tools/PointIndexGrid.h:1430:9: error: expected primary-expression before 'template'
 1430 |         template BaseLeaf::merge<Policy>(rhs);
      |         ^~~~~~~~

Signed-off-by: Mathieu Malaterre <mathieu.malaterre@gmail.com>